plugins {
    id 'java'
    id 'application'
}

group = 'ru.shift'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.2'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'ru.shift.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['--add-modules', 'java.desktop']
}

tasks.named('run') {
    jvmArgs += ['--add-modules=java.desktop']
}

test {
    useJUnitPlatform()
}
