package ru.shift.common.serialization;

enum JsonSerializationTypes {
    REQUEST,
    SUCCESS,
    ERROR,
    NOTIFICATION,

    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    USERS_LIST_REQUEST,
    USERS_LIST_RESPONSE,
    MESSAGE_REQUEST,
    MESSAGE_RESPONSE,

    ERROR_RESPONSE,

    JOIN_NOTIFICATION,
    LEFT_NOTIFICATION,
    DISCONNECT_NOTIFICATION,
    MESSAGE_NOTIFICATION
}
